module.exports = {
  apps: [
    {
      name: "formance-prod",
      script: "dist/backend/src/main.js",
      cwd: "/app/backend",
      env: {
        NODE_ENV: "production",
      },
      error_file: "/app/backend/logs/pm2-error.log",
      out_file: "/app/backend/logs/pm2-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 4000,
    },
    {
      name: "formance-staging",
      script: "dist/backend/src/main.js",
      cwd: "/app/backend",
      env: {
        PORT: 3000,
        NODE_ENV: "staging",
      },
      error_file: "/app/backend/logs/pm2-error.log",
      out_file: "/app/backend/logs/pm2-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 4000,
    },
  ],
  deploy: {
    prod: {
      user: "root",
      host: "66.103.211.113",
      ref: "origin/main",
      repo: "git@github.com:dragsense/formance.git",
      path: "/var/www/formance_dig_usr/data/www/formance.digital.st",
      key: "~/.ssh/ds-server",
      "post-setup": "touch ../shared/.env ../shared/.env.prod ../shared/.env.dev ../shared/.env.shared",
      "post-deploy": "sh ./deploy.sh",
    },
    staging: {
      user: "root",
      host: "66.103.211.113",
      ref: "origin/testing",
      repo: "git@github.com:dragsense/formance.git",
      path: "/var/www/formance_dig_usr/data/www/formance.digital.st",
      key: "~/.ssh/ds-server",
      "post-setup": "touch ../shared/.env ../shared/.env.prod ../shared/.env.dev ../shared/.env.shared",
      "post-deploy": "sh ./deploy.sh",
    },
  },
};
