export enum ESettingType {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
  JSON = 'JSON',
  ARRAY = 'ARRAY',
}

export enum ESettingCategory {
  GENERAL = 'GENERAL',
  APPEARANCE = 'APPEARANCE',
  NOTIFICATIONS = 'NOTIFICATIONS',
  PRIVACY = 'PRIVACY',
  SECURITY = 'SECURITY',
  BUSINESS = 'BUSINESS',
  BILLING = 'BILLING',
  INTEGRATIONS = 'INTEGRATIONS',
}
