// React & Hooks
import { useId, useMemo, useTransition } from "react";

// External libraries
import { XIcon } from "lucide-react";

// UI Components
import { Button } from "@/components/ui/button";

// Custom Hooks
import { useInput } from "@/hooks/use-input";
import { useI18n } from "@/hooks/use-i18n";

// Types
import { type IFacilityInfo } from "@shared/interfaces/facility-info.interface";
import { type TListHandlerStore } from "@/stores";
import { type TFieldConfigObject } from "@/@types/form/field-config.type";

interface IFacilityInfoFiltersProps {
  // Replace 'any' with your specific list data type if available, e.g., TFacilityInfoListData
  store: TListHandlerStore<IFacilityInfo, any, any>;
}

export function FacilityInfoFilters({ store }: IFacilityInfoFiltersProps) {
  const componentId = useId();
  const { t } = useI18n();
  const [, startTransition] = useTransition();

  // Extract store state and actions
  const filteredFields = store.getState().filteredFields;
  const filters = store((state) => state.filters);
  const setFilters = store.getState().setFilters;

  // React 19: Memoized fields to apply custom placeholders and labels via i18n
  const fields = useMemo(
    () =>
      ({
        ...filteredFields,
        search: {
          ...filteredFields.search,
          placeholder: `${t("search")} ${t("email")}...`,
        },
        status: {
          ...filteredFields.status,
          placeholder: t("status"),
        },
      }) as TFieldConfigObject<any>,
    [filteredFields, t],
  );

  // Initialize standardized inputs
  const inputs = useInput({
    fields: fields,
  });

  // React 19: Performance optimized check for active filters
  const hasActiveFilters = useMemo(
    () => Object.keys(filters).length > 0,
    [filters],
  );

  const handleClearFilters = () => {
    startTransition(() => setFilters({}));
  };

  return (
    <div
      className="flex-1 flex items-end gap-2 flex-wrap"
      data-component-id={componentId}
    >
      {/* Dynamic inputs generated by useInput hook */}
      <div className="w-full md:w-64">{inputs.search}</div>

      <div className="w-full md:w-48">{inputs.status}</div>

      {/* Clear Filters Action */}
      {hasActiveFilters && (
        <Button
          variant="outline"
          onClick={handleClearFilters}
          className="hidden lg:flex"
        >
          <XIcon className="h-4 w-4 mr-2" />
          Clear Filters
        </Button>
      )}
    </div>
  );
}
