export enum EResource {
  SESSIONS = 'sessions',
  TASKS = 'tasks',
  CHECKINS = 'checkins',
  BILLINGS = 'billings',
  MEMBERSHIPS = 'memberships',
  MEMBERS = 'members',
  LINK_MEMBERS = 'link_members',
  STAFF = 'staff',
  VIDEO_STREAM = 'video_stream',
  ADVERTISEMENTS = 'advertisements',
  BANNER_SERVICE = 'banner_service',
  FACILITY_INFO = 'facility_info',
  DEVICE_READERS = 'device_readers',
  LOCATIONS = 'locations',
  EQUIPMENT = 'equipment',
  EQUIPMENT_RESERVATIONS = 'equipment_reservations',
  EMAIL_TEMPLATES = 'email_templates',
  PAGES = 'pages',
  FAQS = 'faqs',
  CHAT = 'chat',
  NOTIFICATIONS = 'notifications',
  SERVICE_OFFERS = 'service_offers',
  TRAINER_SERVICES = 'trainer_services',
}
