export enum ERewardType {
  REFERRAL_BONUS = 'REFERRAL_BONUS',
  SIGNUP_BONUS = 'SIGNUP_BONUS',
  MILESTONE_BONUS = 'MILESTONE_BONUS',
  ACTIVITY_BONUS = 'ACTIVITY_BONUS',
  MANUAL_BONUS = 'MANUAL_BONUS',
}

export enum ERewardStatus {
  ACTIVE = 'ACTIVE',
  REDEEMED = 'REDEEMED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum ERewardTier {
  BRONZE = 'BRONZE',
  SILVER = 'SILVER',
  GOLD = 'GOLD',
  PLATINUM = 'PLATINUM',
  DIAMOND = 'DIAMOND',
}
